@startuml dominio

class Charger {
    + ID
    + NumberOfPoints
    + UsageCost
}

class Operator {
    + ID
    + Title
    + Website
    + Comments
}

class Address {
    + Title
    + Town
    + Province
    + Latitude
    + Longitude
}

class UserComment {
    + ID
    + UserName
    + Comment
    + DateCreated
}
class Connection {
    + ID
}

class ConnectionType {
    + ID
    + Title
}

class MediaItem {
    + ID
    + ItemURL
    + ItemThumbnailURL
    + IsEnabled
    + IsVideo
}

Charger -down-> "1" Address : address
Charger -down-> "1" Operator : operator
Charger -down-> "*" UserComment : userComments
Charger -down-> "*" Connection : connections
Charger -down-> "*" MediaItem : mediaItems
Connection -down-> "1" ConnectionType : connectionType


@enduml