@startuml dominio

class Charger {
    + ID
    + NumberOfPoints
    + UsageCost
}

class OperatorInfo {
    + ID
    + Title
    + WebsiteUrl
    + Comments
}

class AddressInfo {
    + Title
    + Town
    + StateOrProvince
    + Latitude
    + Longitude
}

class UserComment {
    + ID
    + UserName
    + Comment
    + DateCreated
}
class Connection {
    + ID
}

class ConnectionType {
    + ID
    + Title
}

Charger -down-> "1" AddressInfo : address
Charger -down-> "1" OperatorInfo : operator
Charger -down-> "*" UserComment : userComments
Charger -down-> "*" Connection : connections
Connection -down-> "1" ConnectionType : connectionType


@enduml